# Setup
title:        Project or Site name
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      "smml"
paginate:     1

# About/contact
author:
  name:       John D. Chodera
  url:        https://choderalab.org

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
