# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:        "statistical mechanics &#128498; machine learning"
tagline:      "smml.io : Exploring the interface of statistical mechanics and machine learning"
url:          https://choderalab.github.io/smml/
baseurl:      https://choderalab.github.io/smml/
paginate:     5

# About/contact
author:
  name:       John D. Chodera
  url:        https://choderalab.org

# Custom vars
version:          2.1.0

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
