# Setup
title:        smml.io
tagline:      Exploring the interface of statistical mechanics and machine learning
url:          https://choderalab.github.io/smml/
baseurl:      https://choderalab.github.io/smml/
paginate:     1

# About/contact
author:
  name:       John D. Chodera
  url:        https://choderalab.org

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
